# Generated by Django 5.0.6 on 2024-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='device_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='latitude',
            field=models.FloatField(default=18.2465),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='longitude',
            field=models.FloatField(default=42.5117),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ppm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
