# Generated by Django 5.0.6 on 2024-09-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0003_sensordata_user_sensordata_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(unique=True)),
                ('device_name', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='device_id',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arduino.device'),
            preserve_default=False,
        ),
    ]
